name: Dev branch pipeline
on:
  push:
    branches:
      - "dev"
    # paths-ignore:
    #   - ".github/**"
  pull_request:
    branches:
      - "dev"
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  # SAST-assessment:
  #   uses: astrearider/gh-workflows/.github/workflows/sonarqube-scan.yml@master
  #   with:
  #     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  #     RUNNER_LABELS: '"self-hosted", "ubuntu"'
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # synk-scan:
  #   uses: astrearider/gh-workflows/.github/workflows/snyk-scan.yml@master
  #   with:
  #     RUNNER_LABELS: '"ubuntu-latest"'
  #   secrets:
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # gosec-scan:
  #   uses: astrearider/gh-workflows/.github/workflows/gosec-scan.yml@master
  #   with:
  #     RUNNER_LABELS: '"ubuntu-latest"'
    
  # gitguardian-scan:
  #   uses: astrearider/gh-workflows/.github/workflows/gitguardian-scan.yml@master
  #   with:
  #     RUNNER_LABELS: '"ubuntu-latest"'
  #   secrets:
  #     GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  # gofmt:
  #   uses: astrearider/gh-workflows/.github/workflows/gofmt.yml@master
  #   with:
  #     RUNNER_LABELS: '"ubuntu-latest"'
      
  docker-build:
    uses: astrearider/gh-workflows/.github/workflows/container-build.yml@master
    with:
      RUNNER_LABELS: '"self-hosted", "ubuntu"'
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}

  sign-image:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: test outputs
        run: | 
          echo "Tags: ${{ needs.docker-build.outputs.tags }}"
          echo "Digest: ${{ needs.docker-build.outputs.digest }}"
    # uses: astrearider/gh-workflows/.github/workflows/sign-image.yml@master
    # with:
    #   RUNNER_LABELS: '"self-hosted", "ubuntu"'
    #   IMAGE_TAGS: ${{ needs.docker-build.outputs.tags }}
    #   IMAGE_DIGEST: ${{ needs.docker-build.outputs.digest }}
    # secrets:
    #   COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    #   COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
  # security-assessment:
  #   uses: astrearider/gh-workflows/.github/workflows/security-assessment.yml@master
  #   secrets:
  #     GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
  # SAST-assessment:
  #   needs: [security-assessment]
  #   uses: astrearider/gh-workflows/.github/workflows/SAST-assessment.yml@master
  #   with:
  #     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # build-scan-image:
  #   needs: [SAST-assessment]
  #   uses: astrearider/gh-workflows/.github/workflows/build-scan-image.yml@master
  #   with:
  #     CONTAINER_REGISTRY_REPO: ${{ vars.CONTAINER_REGISTRY_REPO }}
  #     CONTAINER_LATEST_TAG: ${{ vars.CONTAINER_LATEST_TAG }}
  #     RUNNER_LABEL: ${{ vars.RUNNER_LABEL }}
  #   secrets:
  #     CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}

  # scan-image:
  #   needs: [build-image]
  #   uses: astrearider/gh-workflows/.github/workflows/scan-image.yml@master
  #   with:
  #     CONTAINER_REGISTRY_REPO: ${{ vars.CONTAINER_REGISTRY_REPO }}
  #     CONTAINER_LATEST_TAG: ${{ vars.CONTAINER_LATEST_TAG }}
  #     RUNNER_LABEL: ${{ vars.RUNNER_LABEL }}
  #   secrets:
  #     CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}



  # build-image:
  #   needs: [SAST-assessment]
  #   uses: ./.github/templates/build-image.yml
  #   with:
  #     CONTAINER_REGISTRY_REPO: ${{ vars.CONTAINER_REGISTRY_REPO }}
  #   secrets:
  #     CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  

  # build-push-scan:
  #   uses: ./.github/workflows/build-push-scan-template.yml
  #   needs: [security-assessment]
  #   with:
  #     CONTAINER_REGISTRY_REPO: ${{ vars.CONTAINER_REGISTRY_REPO }}
  #   secrets:
  #     CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  #     CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
